<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Real test gilber</title>
    <!-- <script type="module" crossorigin src="/assets/index-BojbFey_.js"></script>
    <link rel="stylesheet" crossorigin href="/assets/index-DMt9cMri.css"> -->
    <script type="module" crossorigin src="<?= $this->url->get('/dist/assets/index-BojbFey_.js') ?>"></script>
    <link rel="stylesheet" crossorigin href="<?= $this->url->get('/dist/assets/index-DMt9cMri.css') ?>">
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>
